/**
 * lib/content_visibility.ts
 *
 * The single, upstream home for the page-visibility policy: given a page's
 * frontmatter and the build clock, decide where the page is visible. This
 * consolidates logic that was previously scattered across four files behind four
 * ad-hoc frontmatter keys (`rss`, `sitemap`, `noindex`, plus "always rendered").
 *
 * The core idea - a draft is a per-post soft launch. A page that is NOT
 * published (a draft, or a post whose `published_at` is still in the future) is
 * still rendered and reachable by URL, but is absent from every aggregation
 * (listings, RSS, sitemap) and carries `robots: noindex`. To the outside world -
 * random visitors, crawlers, feed readers - it does not exist; the author can
 * still hand the URL to a reviewer. This mirrors how soft-launch *languages*
 * behave (rendered, but dropped from sitemap/RSS/hreflang and noindexed), keyed
 * per-post instead of per-language.
 *
 * Pure functions only - no I/O, no clock of their own (callers pass `now`), so
 * the policy is deterministic and unit-testable.
 *
 * Projects do NOT edit this file. They override the result per-page through the
 * `content_visibility` hook (see lib/hooks.ts), which receives the value of
 * `default_visibility()` and tweaks it.
 */

import type { FrontMatter } from "$lib/static_site";

/** The five independent channels a page can be visible on. */
export type Visibility = {
	/** Emit the HTML page at its URL at all. */
	render: boolean;
	/** Appear in on-page listings / pagination. */
	list: boolean;
	/** Appear in the RSS + JSON feeds. */
	feed: boolean;
	/** Appear in sitemap.xml. */
	sitemap: boolean;
	/** Omit the `robots: noindex` meta (true = indexable). */
	index: boolean;
};

// ---------------------------------------------------------------------------
// "Is this published?" - a compound AND of conjuncts. Add more conjuncts here.
// ---------------------------------------------------------------------------

/** `draft: true` (or its inverse alias `published: false`) marks an unpublished page. */
function not_draft(fm: FrontMatter): boolean {
	if (fm.draft === true) return false;
	if (fm.published === false) return false;
	return true;
}

/**
 * A `published_at` (or `date`) in the future marks the page unpublished - a
 * correctness guard so a future-dated post never leaks before its own date.
 * This is NOT scheduling: nothing auto-rebuilds; the page simply goes public on
 * the first build after its date. Absent/unparseable dates do not suppress.
 */
function date_has_passed(fm: FrontMatter, now: Date): boolean {
	const raw = fm.published_at ?? fm.date;
	if (raw == null) return true;
	const d = raw instanceof Date ? raw : new Date(String(raw));
	if (Number.isNaN(d.getTime())) return true;
	return d.getTime() <= now.getTime();
}

/** Whether a page counts as published (the AND of every conjunct above). */
export function is_published(fm: FrontMatter, now: Date): boolean {
	return not_draft(fm) && date_has_passed(fm, now);
}

// ---------------------------------------------------------------------------
// The default policy, with the defaults applied.
// ---------------------------------------------------------------------------

/**
 * Resolve a page's default visibility from its frontmatter and the build clock.
 *
 * - Published → preserves the historical per-key opt-outs exactly (`rss: false`
 *   drops listings+feeds, `sitemap: false` drops the sitemap, `noindex: true`
 *   drops index+listings+feeds+sitemap), so output is byte-identical.
 * - Not published (draft / future-dated) → built but hidden: rendered and
 *   reachable, but out of every aggregation and noindexed.
 *
 * Note: soft-launch-language `noindex` is applied separately in page_data and is
 * intentionally NOT modeled here - this function is per-page, not per-language.
 */
export function default_visibility(fm: FrontMatter, now: Date): Visibility {
	if (!is_published(fm, now)) {
		return { render: true, list: false, feed: false, sitemap: false, index: false };
	}

	const noindex = fm.noindex === true;
	return {
		render: true,
		list: !(fm.rss === false || noindex),
		feed: !(fm.rss === false || noindex),
		sitemap: !(fm.sitemap === false || noindex),
		index: !noindex,
	};
}

// ---------------------------------------------------------------------------
// Project override seam.
// ---------------------------------------------------------------------------

/** What a project's visibility override receives: the page, plus the default. */
export type VisibilityInput = {
	frontmatter: FrontMatter;
	canonical_path: string;
	lang: string;
	/** The decision `default_visibility` reached - start here, then tweak. */
	default: Visibility;
};

/** A project override: given the default decision, return the final one. */
export type VisibilityOverride = (input: VisibilityInput) => Visibility;

/**
 * Final visibility = the default policy, optionally adjusted by a project
 * override. Pure: the override is injected by the caller (the scripts pass
 * `project_hooks.content_visibility`), so this upstream module never imports
 * project code. An absent override returns the default unchanged.
 */
export function resolve_visibility(
	fm: FrontMatter,
	now: Date,
	canonical_path: string,
	lang: string,
	override?: VisibilityOverride,
): Visibility {
	const base = default_visibility(fm, now);
	return override?.({ frontmatter: fm, canonical_path, lang, default: base }) ?? base;
}
